apiVersion: v2
name: usermanagement
description: A minimal Helm chart for UserManagement application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
  - name: redis
    version: "19.x.x"
    repository: "https://charts.bitnami.com/bitnami"
