server:
  port: 8080

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: 1234
  db: user_management
  sslmode: disable

redis:
  addr: "redis:6379"
  password: ""        
  db: 0

jwt:
  secret_key: "kheyligavi"
  expiration_hours: 24
  refresh_expiration_hours: 168